In [24]:
import pandas as pd
import numpy as np

## Question 1

What's the version of Pandas that you installed?

In [52]:
pd.__version__

'3.0.1'

## Getting the data
For this homework, we'll use the Car Fuel Efficiency dataset.

In [26]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [27]:
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

## Question 2
How many records are in the dataset?

In [56]:
# Records count
df.shape[0]
# df.info()

9704

## Question 3
How many fuel types are presented in the dataset?

In [59]:
# Fuel types
df.fuel_type.nunique()

2

In [60]:
df.nunique()

engine_displacement      36
num_cylinders            14
horsepower              192
vehicle_weight         9704
acceleration            162
model_year               24
origin                    3
fuel_type                 2
drivetrain                2
num_doors                 9
fuel_efficiency_mpg    9704
dtype: int64

## Question 4
How many columns in the dataset have missing values?

In [30]:
# Missing values
missing = df.isnull().sum()
missing = missing[missing > 0]
print(f"The following columns have missing values:\n " + "-"*100 +  f"\n {missing}")

The following columns have missing values:
 ----------------------------------------------------------------------------------------------------
 num_cylinders    482
horsepower       708
acceleration     930
num_doors        502
dtype: int64

In [31]:
# Max fuel efficiency
max_fuel_efficiency_asia = df.loc[df['origin'] == 'Asia', 'fuel_efficiency_mpg'].max()

print(f"The following is the maximum fuel efficiency of vehicles from Asia:\n " + "-"*100 +  f"\n {round(max_fuel_efficiency_asia, 2)}")

The following is the maximum fuel efficiency of vehicles from Asia:
 ----------------------------------------------------------------------------------------------------
 23.76

In [62]:
df.groupby('origin')['fuel_efficiency_mpg'].agg(['min', 'mean', 'max'])

             min       mean        max
origin
Asia    6.886245  14.973830  23.759123
Europe  6.200971  14.942532  25.967222
USA     6.695483  15.040204  24.971452

## Question 6
1. Find the median value of horsepower column in the dataset.
2. Next, calculate the most frequent value of the same horsepower column.
3. Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
4. Now, calculate the median value of horsepower once again.

Has it changed?

In [32]:
# Median value of horsepower
median = df.horsepower.median()

print(f"The following is the median value of horsepower column:\n " + "-"*100 +  f"\n {median}")

The following is the median value of horsepower column:
 ----------------------------------------------------------------------------------------------------
 149.0

In [33]:
# Most frequent value of the horsepower column
mode = df['horsepower'].mode()[0]

print(f"The following is the mode(most frequent) value of horsepower column:\n " + "-"*100 +  f"\n {mode}")

The following is the mode(most frequent) value of horsepower column:
 ----------------------------------------------------------------------------------------------------
 152.0

In [34]:
# Handle missing data (replace missings horsepower values with mode)
print("Missing values in the column 'horsepower': \n ")
print(df['horsepower'].isna().sum())

print("-"*100)
df['horsepower'] = df['horsepower'].fillna(mode)
print("After replacement")
print("-"*100)
print(df['horsepower'].isna().sum())

Missing values in the column 'horsepower':

708
----------------------------------------------------------------------------------------------------
After replacement
----------------------------------------------------------------------------------------------------
0

In [35]:
median = df.horsepower.median()

print(f"The following is the new median value of horsepower column after missing values are replaced:\n " + "-"*100 +  f"\n {median}")

The following is the new median value of horsepower column after missing values are replaced:
 ----------------------------------------------------------------------------------------------------
 152.0

Yes, it's higher

## Question 7
1. Select all the cars from Europe
2. Select only columns vehicle_weight and model_year
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the sum of all the elements of the result?

In [36]:
# Sum of weights
df_cars_from_asia = df.loc[df['origin'] == 'Asia']

df_cars_from_asia = df_cars_from_asia.reset_index(drop=True)
df_cars_from_asia[['vehicle_weight', 'model_year']].head(7)

   vehicle_weight  model_year
0     2714.219310        2016
1     2783.868974        2010
2     3582.687368        2007
3     2231.808142        2011
4     2659.431451        2016
5     2844.227534        2014
6     3761.994038        2019

In [38]:
X = np.array(df_cars_from_asia[['vehicle_weight', 'model_year']].head(7))
X.shape

(7, 2)

$$
w = (X^T X)^{-1} X^T y
$$

In [65]:
# X transpose 
XTX = X.T @ X


# Invert XTX
XTX_inv = np.linalg.inv(XTX)

# array
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])


# weight
w = XTX_inv @ X.T @ y
print(w[0] + w[1])
# sum(w)

0.5187709081074016